name: GitHub Pages

on:
  push:
    branches:
    - '!gh-pages'
  pull_request:
    branches:
    - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: git config --global user.name "Ken Matsui"
    - run: git config --global user.email "26405363+matken11235@users.noreply.github.com"
    - run: npm install
    - run: npm run build
    - run: cp assets/robots.txt _book
    - run: cp -r .circleci _book/
    - run: npm run publish
